#include <vector>
#include <string>
#include <Python.h>
#include "doxygen.h"
#include "textstream.h"

/**
 * \brief Helper function to convert the vector of TextStream objects
 *        containing the XML output generated by doxygen to a Python list.
 * \return Python list containing the generated XML output as bytes. Returns
 *         NoneType if any errors occur during population of the list
 */
static PyObject *convert_xml_data_to_pyobject() {
  std::vector<TextStream> xml_files = generateOutput();
  Py_ssize_t total_files = xml_files.size();

  PyObject *xml_files_list = PyList_New(total_files);
  if (!xml_files_list) {
    PyErr_SetString(
      PyExc_RuntimeError, "Error during XML output list creation");
    return NULL;
  }

  for (Py_ssize_t i = 0 ; i < total_files; ++i) {
    PyObject *py_xml_file_content = PyBytes_FromStringAndSize(
      xml_files[i].c_str(), xml_files[i].size());

    if (PyList_SetItem(xml_files_list, i, py_xml_file_content) != 0) {
      Py_DecRef(xml_files_list);
      PyErr_SetString(
        PyExc_RuntimeError, "Error during XML output list population");
      return NULL;
    }
  }

  return xml_files_list;
}

/**
 * \brief Exported entry point function that can be called directly from
 *        Python to generate XML output based on the provided Doxyfile path.
 * \param [in] self Reference to Python module that will contain this function
 * \param [in] args Tuple of arguments passed to this function
 * \return Python object containing the generated XML data
 */
extern "C" PyObject *generate_xml_output(PyObject *self, PyObject *args) {
  if (!Py_IsInitialized()) {
    Py_Initialize();
  }

  char *doxyfileContent = NULL;
  if(!PyArg_ParseTuple(args, "s", &doxyfileContent)) {
    PyErr_SetString(PyExc_ValueError, "Argument must be a string");
    return NULL;
  }

  initDoxygen();
  if (readConfiguration(doxyfileContent) != 0) {
    PyErr_SetString(
      PyExc_RuntimeError, "Doxygen configuration file is malformatted");
    return NULL;
  }
  checkConfiguration();
  adjustConfiguration();
  parseInput();

  PyObject *generated_xml_files = convert_xml_data_to_pyobject();
  return generated_xml_files;
}

static PyMethodDef generateXmlOutput[] = {
  {"generate_xml_output", generate_xml_output, METH_VARARGS,
  "Generate doxygen XML output and return it directly to Python"},
  {NULL, NULL, 0, NULL}
};

static struct PyModuleDef doxygenModule = {
  PyModuleDef_HEAD_INIT,
  "doxygen",
  "Generate doxygen XML output and return it directly to Python",
  -1,
  generateXmlOutput
};

PyMODINIT_FUNC PyInit_libdoxygen(void) {
  return PyModule_Create(&doxygenModule);
}
