#include <vector>
#include <string>
#include <Python.h>
#include "doxygen.h"
#include "textstream.h"

/**
 * \brief Helper function to convert the vector of TextStream objects
 *        containing the XML output generated by doxygen to a Python list.
 * \return Python list containing the generated XML output as bytes. Returns
 *         NoneType if any errors occur during population of the list
 */
static PyObject *convert_xml_data_to_pyobject() {
  std::vector<TextStream> xml_files = generateOutput();

  Py_ssize_t total_files = xml_files.size();

  if (!Py_IsInitialized()) {
    Py_Initialize();
  }

  PyObject *xml_files_list = PyList_New(total_files);
  if (!xml_files_list) {
    return Py_None;
  }

  for (Py_ssize_t i = 0 ; i < total_files; ++i) {
    PyObject *py_xml_file_content = PyBytes_FromStringAndSize(
      xml_files[i].c_str(), xml_files[i].size());

    if (PyList_SetItem(xml_files_list, i, py_xml_file_content) != 0) {
      Py_DecRef(xml_files_list);
      return Py_None;
    }
  }

  return xml_files_list;
}

/**
 * \brief Exported entry point function that can be called directly from
 *        Python to generate XML output based on the provided Doxyfile path.
 * \param [in] doxyfilePath Path to the doxygen configuration file
 * \return Python object containing the generated XML data
 */
extern "C" PyObject *generate_xml_output(char *doxyfilePath) {
  int argc = 2;
  char *argv[2];

  char *doxygen = const_cast<char*>("doxygen");
  argv[0] = doxygen;
  argv[1] = doxyfilePath;

  initDoxygen();
  readConfiguration(argc, argv);
  checkConfiguration();
  adjustConfiguration();
  parseInput();

  PyObject *generated_xml_files = convert_xml_data_to_pyobject();
  return generated_xml_files;
}
